# jmall-common-web 模块自动配置
# SpringDoc OpenAPI 默认配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-flat-param-object: true
