package com.jmall.coupon.service.impl;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl; import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.jmall.coupon.entity.*; import com.jmall.coupon.mapper.*; import com.jmall.coupon.service.CouponService; import com.jmall.common.core.constant.RedisConstants; import com.jmall.common.core.exception.BusinessException; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.List;
@Service @RequiredArgsConstructor
public class CouponServiceImpl extends ServiceImpl<CouponMapper,Coupon> implements CouponService {
 private final UserCouponMapper userCouponMapper;
 public UserCoupon receive(Long couponId,Long userId){ Coupon c=getById(couponId); if(c==null||c.getStatus()==3||LocalDateTime.now().isBefore(c.getStartTime())||LocalDateTime.now().isAfter(c.getEndTime())) throw new BusinessException("优惠券不可领取"); long count=userCouponMapper.selectCount(new LambdaQueryWrapper<UserCoupon>().eq(UserCoupon::getCouponId,couponId).eq(UserCoupon::getUserId,userId)); if(c.getPerUserLimit()!=null&&count>=c.getPerUserLimit()) throw new BusinessException("已达到领取上限"); if(c.getTotalCount()!=null&&c.getTotalCount()>0&&c.getIssuedCount()>=c.getTotalCount()) throw new BusinessException("优惠券已领完"); UserCoupon u=new UserCoupon(); u.setUserId(userId);u.setCouponId(couponId);u.setCouponName(c.getName());u.setType(c.getType());u.setDiscountAmount(c.getDiscountAmount());u.setDiscountRate(c.getDiscountRate());u.setMinAmount(c.getMinAmount());u.setStatus(0);u.setReceivedTime(LocalDateTime.now());u.setExpireTime(c.getValidDays()!=null?LocalDateTime.now().plusDays(c.getValidDays()):c.getValidEndTime()); userCouponMapper.insert(u); c.setIssuedCount(c.getIssuedCount()+1); updateById(c); return u; }
 public List<UserCoupon> userCoupons(Long userId){return userCouponMapper.selectList(new LambdaQueryWrapper<UserCoupon>().eq(UserCoupon::getUserId,userId).orderByDesc(UserCoupon::getReceivedTime));}
 public UserCoupon getUserCoupon(Long id){return userCouponMapper.selectById(id);}
 public void use(Long id,String orderNo){UserCoupon u=getUserCoupon(id); if(u==null||u.getStatus()!=0||u.getExpireTime().isBefore(LocalDateTime.now())) throw new BusinessException("优惠券不可使用");u.setStatus(1);u.setOrderNo(orderNo);u.setUseTime(LocalDateTime.now());userCouponMapper.updateById(u);Coupon c=getById(u.getCouponId());if(c!=null){c.setUsedCount(c.getUsedCount()+1);updateById(c);}}
 public void refund(Long id){UserCoupon u=getUserCoupon(id);if(u==null||u.getStatus()!=1)throw new BusinessException("优惠券未核销");u.setStatus(0);u.setOrderNo(null);u.setUseTime(null);userCouponMapper.updateById(u);Coupon c=getById(u.getCouponId());if(c!=null){c.setUsedCount(Math.max(0,c.getUsedCount()-1));updateById(c);}}
 public BigDecimal calculate(Long id,BigDecimal amount){UserCoupon u=getUserCoupon(id);if(u==null||u.getStatus()!=0||amount.compareTo(u.getMinAmount())<0) return BigDecimal.ZERO; if(u.getType()==2)return amount.multiply(BigDecimal.ONE.subtract(u.getDiscountRate())).setScale(2,BigDecimal.ROUND_HALF_UP);return u.getDiscountAmount();}
}
