<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jmall</groupId>
        <artifactId>jmall</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>jmall-user</artifactId>
    <name>jmall-user</name>
    <description>J-Mall 用户服务 - 用户信息/收货地址/收藏</description>

    <dependencies>
        <dependency>
            <groupId>com.jmall</groupId>
            <artifactId>jmall-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jmall</groupId>
            <artifactId>jmall-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jmall</groupId>
            <artifactId>jmall-common-redis</artifactId>
        </dependency>
        <!-- 公共安全模块（UserContextHolder + Feign Token透传） -->
        <dependency>
            <groupId>com.jmall</groupId>
            <artifactId>jmall-common-security</artifactId>
        </dependency>
        <!-- 用户共享 API（DTO） -->
        <dependency>
            <groupId>com.jmall</groupId>
            <artifactId>jmall-api-user</artifactId>
        </dependency>
        <!-- Nacos 注册中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!-- Nacos 配置中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>